import { ListLegal, SubtitleLegal, TextLegal, TitleLegal } from "@/shared/ui/Legal"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Discover how we collect, use, and protect your personal information when you use BoostClock."
};

const PolicyPage = () => {
  return (
    <>
        <TitleLegal>Privacy Policy</TitleLegal>
        <TextLegal>Last updated: December 14, 2025.</TextLegal>
        <TextLegal>Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal information when you use BoostClock.</TextLegal>
        <SubtitleLegal>1. Information We Collect</SubtitleLegal>
        <TextLegal>We collect the following types of information:</TextLegal>
        <ListLegal type="unordered">
            <li>Account Information: If you create an account, we collect your email address and authentication data (via email/password or Google account).</li>
            <li>Local Data: For non-authenticated users, we store settings, tasks, achievements, and statistics in your browser's localStorage.</li>
            <li>Usage Data: We do not actively collect analytics or tracking data. Basic technical logs may be generated by Firebase for security and reliability purposes.</li>
        </ListLegal>
        <SubtitleLegal>2. How We Use Your Information</SubtitleLegal>
        <TextLegal>We use your information for the following purposes:</TextLegal>
        <ListLegal type="unordered">
            <li>To provide and maintain the service.</li>
            <li>To authenticate users and manage accounts.</li>
            <li>To store and sync your data across devices (if you are authenticated).</li>
            <li>To improve the service and develop new features.</li>
        </ListLegal>
        <SubtitleLegal>3. Data Storage</SubtitleLegal>
        <TextLegal>Your data is stored in the following ways:</TextLegal>
        <ListLegal type="unordered">
            <li>LocalStorage: For non-authenticated users, data is stored locally on your device.</li>
            <li>Firebase: For authorized users, data is stored in Firebase, a cloud service provided by Google.</li>
        </ListLegal>
        <SubtitleLegal>4. Data Security</SubtitleLegal>
        <TextLegal>We take reasonable measures to protect your data:</TextLegal>
        <ListLegal type="unordered">
            <li>Firebase uses industry-standard security practices to protect your data.</li>
            <li>LocalStorage data is stored locally in your browser and is not transmitted to our servers unless you choose to authenticate and sync your data.</li>
        </ListLegal>
        <SubtitleLegal>5. Your Rights</SubtitleLegal>
        <TextLegal>You have the following rights regarding your data:</TextLegal>
        <ListLegal type="unordered">
            <li>Access: You may request a copy of your data by contacting us.</li>
            <li>Deletion: You can delete your account and all associated data.</li>
            <li>Export: You can request an export of your data in a readable format.</li>
        </ListLegal>
        <TextLegal>To exercise these rights, please contact us at <a href="mailto:flionx@mail.ru" className="underline">flionx@mail.ru</a>.</TextLegal>
        <SubtitleLegal>6. Cookies and Tracking</SubtitleLegal>
        <TextLegal>We do not use cookies or similar tracking technologies at this time.</TextLegal>
        <SubtitleLegal>7. Sharing Data with Third Parties</SubtitleLegal>
        <TextLegal>We do not share your data with third parties, except for Firebase (Google), which is used solely for authentication and data storage.</TextLegal>
        <SubtitleLegal>8. Changes to This Policy</SubtitleLegal>
        <TextLegal>We may update this Privacy Policy from time to time. The updated version will be effective immediately upon posting on this page. We will notify you of significant changes via email or a notice within the service.</TextLegal>
    </>
  )
}

export default PolicyPage